### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jakubfijalkowski** [leancodepl/contractsgenerator#36]
The generator does not work on git-bash.

**Comment by shilangyu** [comment]
Since we already require that `dotnet` has to be installed, maybe the script should be written in C#? Assuming C# can be ran as a script and that the stdlib has needed functions.

**Comment by jakubfijalkowski** [comment]
Unfortunately, dotnet does not easily allow to run C# as scripts without third party plugins - we have to keep the shell scripts unfortunately.

Also,the issue, it seems, doesn't really relate to the script - MS build/Buildalyzer behaves differently.
